spring:
  datasource:
    url: jdbc:h2:mem:water-bets
    username: sa
    password:
    driverClassName: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true
      path: /h2-console
